"""Code to Zip decoded NC files."""

import xml.etree.ElementTree as ET
from contextlib import contextmanager
from io import BytesIO
from pathlib import Path
from zipfile import ZIP_STORED, ZipFile


class ZipNCFilesError(Exception):
    """Raised when there is an issue zipping the NC files."""


class ZipNCFiles:
    """Methods to zip newly decoded NC files from the Coriolis Decoder."""

    def __init__(self, wmonum: str, xml_location: str = "/mnt/data/output/xml"):
        """Initialise the instance with the wmonum."""
        self.wmonum = wmonum
        self.xml_location = xml_location

    def fetch_all_nc_paths(self) -> list[str]:
        """Parse the XML and return a list of paths generated by the decoder."""
        latest_xml_file = max(Path(self.xml_location).iterdir(), key=lambda file: file.stat().st_mtime)
        with open(latest_xml_file) as xml_file:
            root = ET.fromstring(xml_file.read())
            return [item.text for item in root.iter() if item.tag.startswith("output")]

    @contextmanager
    def zip_buffer(self):
        """Provide an open BytesIO object for the zipfile creation."""
        zip_buffer = BytesIO()
        try:
            with ZipFile(zip_buffer, "w", compression=ZIP_STORED) as zipfile:
                yield zipfile, zip_buffer
        finally:
            zip_buffer.seek(0)

    def zip_all_nc_files(self) -> tuple[BytesIO, str]:
        """Zip all decoded NC files and return to the app so FastAPI can stream it."""
        try:
            nc_paths = self.fetch_all_nc_paths()

            with self.zip_buffer() as (zipfile, buffer):
                for filepath in nc_paths:
                    zipfile.write(filepath)

            filename = f"{self.wmonum}.zip"
            return buffer, filename

        except Exception as exc:
            raise ZipNCFilesError(exc) from None
