% ------------------------------------------------------------------------------
% Create and add the vertical sampling scheme information to the profiles of the
% Iridium floats.
%
% SYNTAX :
%  [o_tabProfiles] = add_vertical_sampling_scheme_3T_2T_228_229(a_tabProfiles)
%
% INPUT PARAMETERS :
%   a_tabProfiles : input profile structures
%
% OUTPUT PARAMETERS :
%   o_tabProfiles : output profile structures
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHOR : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   05/13/2024 - RNU - creation
% ------------------------------------------------------------------------------
function [o_tabProfiles] = add_vertical_sampling_scheme_3T_2T_228_229(a_tabProfiles)

% output parameters initialization
o_tabProfiles = [];

% current float WMO number
global g_decArgo_floatNum;

% current cycle number
global g_decArgo_cycleNum;

% default values
global g_decArgo_presDef;


% add the vertical sampling scheme for each profile
for idP = 1:length(a_tabProfiles)
   prof = a_tabProfiles(idP);
   
   [configNames, configValues] = get_float_config_ir_sbd(prof.cycleNumber);
   if (~isempty(configNames))
      
      vssText = [];
      if (prof.primarySamplingProfileFlag == 1)
         vssText = 'Primary sampling: averaged';
      elseif (prof.primarySamplingProfileFlag == 2)
         vssText = 'Near-surface sampling: averaged, unpumped';
      else
         vssText = 'Secondary sampling: averaged';
      end
      
      % retrieve needed information from configuration
      descSamplingPeriod = get_config_value('CONFIG_PM05', configNames, configValues);
      ascSamplingPeriod = get_config_value('CONFIG_PM07', configNames, configValues);
      parkPres = get_config_value('CONFIG_PM08', configNames, configValues);
      profilePres = get_config_value('CONFIG_PM09', configNames, configValues);
      threshold1 = get_config_value('CONFIG_FR11', configNames, configValues);
      threshold2 = get_config_value('CONFIG_FR10', configNames, configValues);
      threshold3 = get_config_value('CONFIG_FR09', configNames, configValues);
      threshold4 = get_config_value('CONFIG_FR08', configNames, configValues);
      thick1 = get_config_value('CONFIG_FR16', configNames, configValues);
      thick2 = get_config_value('CONFIG_FR15', configNames, configValues);
      thick3 = get_config_value('CONFIG_FR14', configNames, configValues);
      thick4 = get_config_value('CONFIG_FR13', configNames, configValues);
      thick5 = get_config_value('CONFIG_FR12', configNames, configValues);
      
      % if not set, use a default sampling period of 10 sec
      if (isempty(ascSamplingPeriod))
         ascSamplingPeriod = 10;
      end
      if (isempty(descSamplingPeriod))
         descSamplingPeriod = ascSamplingPeriod;
      end
      
      if (prof.direction == 'A')

         % ascending profile

         if (prof.rbrFlag == 0)
            % SBE41 or SBE61

            if (~isempty(ascSamplingPeriod) && ~isempty(profilePres) && ...
                  ~isempty(threshold1) && ~isempty(threshold2) && ...
                  ~isempty(threshold3) && ~isempty(threshold4) && ...
                  ~isempty(thick1) && ~isempty(thick2) && ~isempty(thick3) && ...
                  ~isempty(thick4) && ~isempty(thick5) && ...
                  (prof.presCutOffProf ~= g_decArgo_presDef) && ...
                  (prof.presCutOffProf ~= -g_decArgo_presDef))

               if (prof.primarySamplingProfileFlag == 2)
                  description = sprintf( ...
                     ['%d sec sampling, %.1f dbar avg from %.1f dbar to surface'], ...
                     ascSamplingPeriod, thick1, prof.presCutOffProf);
               else
                  description = sprintf( ...
                     ['%d sec sampling;' ...
                     '%.1f dbar avg from %d dbar to %d dbar;' ...
                     '%.1f dbar avg from %d dbar to %d dbar;' ...
                     '%.1f dbar avg from %d dbar to %d dbar;', ...
                     '%.1f dbar avg from %d dbar to %d dbar;', ...
                     '%.1f dbar avg from %d dbar to %.1f dbar'], ...
                     ascSamplingPeriod, ...
                     thick5, profilePres, threshold4, ...
                     thick4, threshold4, threshold3, ...
                     thick3, threshold3, threshold2, ...
                     thick2, threshold2, threshold1, ...
                     thick1, threshold1, prof.presCutOffProf);
               end
            else
               description = '';
               fprintf('WARNING: Float #%d Cycle #%d: Missing information to create the description of the vertical sampling scheme\n', ...
                  g_decArgo_floatNum, ...
                  g_decArgo_cycleNum);
            end
         else
            % RBR

            if (~isempty(ascSamplingPeriod) && ~isempty(profilePres) && ...
                  ~isempty(threshold1) && ~isempty(threshold2) && ...
                  ~isempty(threshold3) && ~isempty(threshold4) && ...
                  ~isempty(thick1) && ~isempty(thick2) && ~isempty(thick3) && ...
                  ~isempty(thick4) && ~isempty(thick5))

               description = sprintf( ...
                  ['%d sec sampling;' ...
                  '%.1f dbar avg from %d dbar to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar;', ...
                  '%.1f dbar avg from %d dbar to %d dbar;', ...
                  '%.1f dbar avg from %d dbar to surface'], ...
                  ascSamplingPeriod, ...
                  thick5, profilePres, threshold4, ...
                  thick4, threshold4, threshold3, ...
                  thick3, threshold3, threshold2, ...
                  thick2, threshold2, threshold1, ...
                  thick1, threshold1);
            else
               description = '';
               fprintf('WARNING: Float #%d Cycle #%d: Missing information to create the description of the vertical sampling scheme\n', ...
                  g_decArgo_floatNum, ...
                  g_decArgo_cycleNum);
            end
         end

      else

         % descending profile
         
         if (~isempty(descSamplingPeriod) && ~isempty(parkPres) && ...
               ~isempty(threshold1) && ~isempty(threshold2) && ...
               ~isempty(threshold3) && ~isempty(threshold4) && ...
               ~isempty(thick1) && ~isempty(thick2) && ~isempty(thick3) && ...
               ~isempty(thick4) && ~isempty(thick5))

            if (parkPres > threshold4)
               description = sprintf( ...
                  ['%d sec sampling;' ...
                  '%.1f dbar avg from surface to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar'], ...
                  descSamplingPeriod, ...
                  thick1, threshold1, ...
                  thick2, threshold1, threshold2, ...
                  thick3, threshold2, threshold3, ...
                  thick4, threshold3, threshold4, ...
                  thick5, threshold4, parkPres);
            elseif (parkPres > threshold3)
               description = sprintf( ...
                  ['%d sec sampling;' ...
                  '%.1f dbar avg from surface to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar'], ...
                  descSamplingPeriod, ...
                  thick1, threshold1, ...
                  thick2, threshold1, threshold2, ...
                  thick3, threshold2, threshold3, ...
                  thick4, threshold3, parkPres);
            elseif (parkPres > threshold2)
               description = sprintf( ...
                  ['%d sec sampling;' ...
                  '%.1f dbar avg from surface to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar'], ...
                  descSamplingPeriod, ...
                  thick1, threshold1, ...
                  thick2, threshold1, threshold2, ...
                  thick3, threshold2, parkPres);
            elseif (parkPres > threshold1)
               description = sprintf( ...
                  ['%d sec sampling;' ...
                  '%.1f dbar avg from surface to %d dbar;' ...
                  '%.1f dbar avg from %d dbar to %d dbar'], ...
                  descSamplingPeriod, ...
                  thick1, threshold1, ...
                  thick2, threshold1, parkPres);
            else
               description = sprintf( ...
                  ['%d sec sampling;' ...
                  '%.1f dbar avg from surface to %d dbar'], ...
                  descSamplingPeriod, thick1, parkPres);
            end
         else
            description = '';
            fprintf('WARNING: Float #%d Cycle #%d: Missing information to create the description of the vertical sampling scheme\n', ...
               g_decArgo_floatNum, ...
               g_decArgo_cycleNum);
         end
      end

      vssText = [vssText ' [' description ']'];
      
      a_tabProfiles(idP).vertSamplingScheme = vssText;
      
   end
end

o_tabProfiles = a_tabProfiles;

return
