% ------------------------------------------------------------------------------
% Create configuration parameter lists of decoder names and NetCDF names.
%
% SYNTAX :
%  [o_decArgoConfParamNames, o_ncConfParamNames, o_ncConfParamIds] = ...
%    create_config_param_names_pfv2
%
% INPUT PARAMETERS :
%    a_decoderId : decoder Id
%
% OUTPUT PARAMETERS :.
%    o_decArgoConfParamNames : internal configuration parameter names
%    o_ncConfParamNames      : NetCDF configuration parameter names
%    o_ncConfParamIds        : NetCDF configuration parameter Ids
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHOR : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   10/07/2024 - RNU - creation
% ------------------------------------------------------------------------------
function [o_decArgoConfParamNames, o_ncConfParamNames, o_ncConfParamIds] = ...
   create_config_param_names_pfv2

% output parameters initialization
o_decArgoConfParamNames = [];
o_ncConfParamNames = [];
o_ncConfParamIds = [];

% current float WMO number
global g_decArgo_floatNum;

% output NetCDF configuration parameter Ids
global g_decArgo_outputNcConfParamId;

% output NetCDF configuration parameter labels
global g_decArgo_outputNcConfParamLabel;


% % create configuration names for decoder and associated one for NetCDF
% configIds = [ ...
%    {'MISSION.P0'} ...
%    {'MISSION-PRESSURE_DETECTION.P0'} ...
%    {'MISSION-PRESSURE_DETECTION.P1'} ...
%    {'MISSION-PRESSURE_DETECTION.P2'} ...
%    {'MISSION-INITIALIZATION.P0'} ...
%    {'MISSION-LOOPXX-CYCLEXX.P1'} ...
%    {'MISSION-LOOPXX-CYCLEXX.P2'} ...
%    {'MISSION-LOOPXX-CYCLEXX-TRANSMISSION01.P0'} ...
%    {'MISSION-LOOPXX-CYCLEXX-BUOYANCY_RED.P0'} ...
%    {'MISSION-LOOPXX-CYCLEXX-DESC_PARK.P0'} ...
%    {'MISSION-LOOPXX-CYCLEXX-DESC_PARK.P1'} ...
%    {'MISSION-LOOPXX-CYCLEXX-PARK_DRIFT.P0'} ...
%    {'MISSION-LOOPXX-CYCLEXX-PARK_DRIFT.P1'} ...
%    {'MISSION-LOOPXX-CYCLEXX-PARK_DRIFT.P2'} ...
%    {'MISSION-LOOPXX-CYCLEXX-DESC_PROF.P0'} ...
%    {'MISSION-LOOPXX-CYCLEXX-DESC_PROF.P1'} ...
%    {'MISSION-LOOPXX-CYCLEXX-PROF_DRIFT.P0'} ...
%    {'MISSION-LOOPXX-CYCLEXX-PROF_DRIFT.P1'} ...
%    {'MISSION-LOOPXX-CYCLEXX-PROF_DRIFT.P2'} ...
%    {'MISSION-LOOPXX-CYCLEXX-ASCENT.P0'} ...
%    {'MISSION-LOOPXX-CYCLEXX-ASCENT.P1'} ...
%    {'MISSION-LOOPXX-CYCLEXX-IN_AIR.P0'} ...
%    {'MISSION-LOOPXX-CYCLEXX-IN_AIR.P1'} ...
%    {'MISSION-LOOPXX-CYCLEXX-END_OF_CYCLE.P0'} ...
%    {'MISSION-END_OF_LIFE.P0'} ...
%    {'TECHNICAL-BUOYANCY_RED.P0'} ...
%    {'TECHNICAL-BUOYANCY_RED.P1'} ...
%    {'TECHNICAL-BUOYANCY_RED.P2'} ...
%    {'TECHNICAL-BUOYANCY_RED.P3'} ...
%    {'TECHNICAL-DESCENT.P0'} ...
%    {'TECHNICAL-DRIFT.P0'} ...
%    {'TECHNICAL-REPOSITIONING.P0'} ...
%    {'TECHNICAL-ASCENT.P0'} ...
%    {'TECHNICAL-ASCENT-SURFACE.P0'} ...
%    {'TECHNICAL-ASCENT-SURFACE.P1'} ...
%    {'TECHNICAL-EMERGENCE.P0'} ...
%    {'TECHNICAL-IN_AIR.P0'} ...
%    {'TECHNICAL-TRANSMISSION.P0'} ...
%    {'TECHNICAL-TRANSMISSION.P1'} ...
%    {'TECHNICAL-TRANSMISSION.P2'} ...
%    {'TECHNICAL-TRANSMISSION.P3'} ...
%    {'TECHNICAL-TRANSMISSION.P4'} ...
%    {'TECHNICAL-TRANSMISSION.P5'} ...
%    {'TECHNICAL-TRANSMISSION-RUDICS.P0'} ...
%    {'TECHNICAL-TRANSMISSION-RUDICS.P1'} ...
%    {'TECHNICAL-TRANSMISSION-SBD.P0'} ...
%    {'TECHNICAL-EMERGENCY_ASCENT.P0'} ...
%    {'TECHNICAL-EMERGENCY_ASCENT.P1'} ...
%    {'TECHNICAL-LOGGER.P0'} ...
%    {'TECHNICAL-LOGGER.P1'} ...
%    {'TECHNICAL-SECURITY.P0'} ...
%    {'TECHNICAL-SECURITY.P1'} ...
%    {'TECHNICAL-SECURITY.P2'} ...
%    {'TECHNICAL-SECURITY.P3'} ...
%    {'TECHNICAL-SECURITY-GROUNDING.P0'} ...
%    {'TECHNICAL-SECURITY-GROUNDING.P1'} ...
%    {'TECHNICAL-SECURITY-GROUNDING.P2'} ...
%    {'TECHNICAL-SECURITY-GROUNDING.P3'} ...
%    {'TECHNICAL-SECURITY-GROUNDING.P4'} ...
%    {'TECHNICAL-SECURITY-GROUNDING.P5'} ...
%    {'TECHNICAL-SECURITY-GROUNDING.P6'} ...
%    {'TECHNICAL-HYDRAULIC.P0'} ...
%    {'TECHNICAL-HYDRAULIC.P1'} ...
%    {'SENSORS-SENSORXX.P0'} ...
%    {'SENSORS-SENSORXX.P1'} ...
%    {'SENSORS-SENSORXX.P2'} ...
%    {'SENSORS-SENSORXX-DESCENT.P0'} ...
%    {'SENSORS-SENSORXX-DESCENT.P1'} ...
%    {'SENSORS-SENSORXX-DESCENT-ZONEN.P0'} ...
%    {'SENSORS-SENSORXX-DESCENT-ZONEN.P1'} ...
%    {'SENSORS-SENSORXX-DESCENT-ZONEN.P2'} ...
%    {'SENSORS-SENSORXX-DESCENT-ZONEN.P3'} ...
%    {'SENSORS-SENSORXX-DESCENT-ZONEN.P4'} ...
%    {'SENSORS-SENSORXX-DESCENT-ZONEN.P5'} ...
%    {'SENSORS-SENSORXX-ASCENT.P0'} ...
%    {'SENSORS-SENSORXX-ASCENT-ZONEN.P0'} ...
%    {'SENSORS-SENSORXX-ASCENT-ZONEN.P1'} ...
%    {'SENSORS-SENSORXX-ASCENT-ZONEN.P2'} ...
%    {'SENSORS-SENSORXX-ASCENT-ZONEN.P3'} ...
%    {'SENSORS-SENSORXX-ASCENT-ZONEN.P4'} ...
%    {'SENSORS-SENSORXX-ASCENT-ZONEN.P5'} ...
%    {'SENSORS-SENSORXX-PARK_DRIFT.P0'} ...
%    {'SENSORS-SENSORXX-PROF_DRIFT.P0'} ...
%    {'SENSORS-SENSORXX-IN_AIR.P0'} ...
%    {'SENSORS-SENSORXX-IN_AIR.P1'} ...
%    {'SENSORS-SENSORXX-TECHNICAL.P0'} ...
%    {'SENSORS-SENSORXX-TECHNICAL.P1'} ...
%    {'SENSORS-SENSORXX-TECHNICAL.P2'} ...
%    {'SENSORS-SENSORXX-TECHNICAL.P3'} ...
%    {'SENSORS-SENSOR01-SPECIFIC.P0'} ...
%    {'ICE.P0'} ...
%    {'ICE.P1'} ...
%    {'ICE.P2'} ...
%    {'ICE.P3'} ...
%    {'ICE.P4'} ...
%    {'ICE.P5'} ...
%    {'ICE-ISA.P0'} ...
%    {'ICE-ISA.P1'} ...
%    {'ICE-ISA.P2'} ...
%    {'ICE-ISA.P3'} ...
%    {'ICE-ISA.P4'} ...
%    {'ICE-HANGING.P0'} ...
%    {'ICE-HANGING.P1'} ...
%    {'ICE-HANGING.P2'} ...
%    {'ICE-HANGING.P3'} ...
%    {'ICE-SAT_MASK.P0'} ...
%    {'SELFTEST.P0'} ...
%    {'SELFTEST.P1'} ...
%    {'SELFTEST.P2'} ...
%    {'SELFTEST.P3'} ...
%    {'SELFTEST.P4'} ...
%    {'SELFTEST.P5'} ...
%    {'SELFTEST.P6'} ...
%    {'SELFTEST.P7'} ...
%    {'SELFTEST.P8'} ...
%    {'ALARMS-THRESHOLD.P0'} ...
%    {'ALARMS-THRESHOLD.P1'} ...
%    {'ALARMS-THRESHOLD.P2'} ...
%    {'ALARMS-THRESHOLD.P3'} ...
%    {'ALARMS-THRESHOLD.P4'} ...
%    {'ALARMS-THRESHOLD.P5'} ...
%    {'ALARMS-THRESHOLD.P6'} ...
%    {'ALARMS-THRESHOLD.P7'} ...
%    {'ALARMS-THRESHOLD.P8'} ...
%    {'ALARMS-THRESHOLD.P9'} ...
%    {'ALARMS-THRESHOLD.P10'} ...
%    {'ALARMS-END_OF_LIFE.P0'} ...
%    {'ALARMS-END_OF_LIFE.P2'} ...
%    {'ALARMS-END_OF_LIFE.P4'} ...
%    {'ALARMS-END_OF_LIFE.P10'} ...
%    {'ALARMS-END_OF_LIFE.P11'} ...
%    {'ALARMS-END_OF_LIFE.P21'} ...
%    ];
% 
% decConfNames = [];
% ncConfNames = [];
% ncConfIds = [];
% if (~isempty(configIds))
%    for idC = 1:length(configIds)
%       idParamName = find(strcmp(g_decArgo_outputNcConfParamId, configIds{idC}) == 1);
%       if (isempty(idParamName))
%          fprintf('ERROR: Float #%d: Configuration parameter not managed ''%s''\n', ...
%             g_decArgo_floatNum, ...
%             configIds{idC});
%          continue
%       end
%       decConfNames{end+1} = configIds{idC};
%       ncConfNames{end+1} = g_decArgo_outputNcConfParamLabel{idParamName};
%       ncConfIds = [ncConfIds g_decArgo_outputNcConfParamId(idParamName)];
%    end
% end

decConfNames = g_decArgo_outputNcConfParamId;
ncConfNames = g_decArgo_outputNcConfParamLabel;
ncConfIds = g_decArgo_outputNcConfParamId;

% output for check
% for id = 1:length(decConfNames)
%    fprintf('%s;%s\n', decConfNames{id}, ncConfNames{id});
% end

% update output parameters
o_decArgoConfParamNames = decConfNames;
o_ncConfParamNames = ncConfNames;
o_ncConfParamIds = ncConfIds;

return
