% ------------------------------------------------------------------------------
% Get the basic structure to store APEX APF11 Ice thermal detection information.
%
% SYNTAX :
%  [o_thermalDetect] = get_ice_thermal_detect_apx_apf11_init_struct
%
% INPUT PARAMETERS :
%
% OUTPUT PARAMETERS :
%   o_thermalDetect : APEX APF11 Ice thermal detection structure
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHOR : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   01/07/2025 - RNU - creation
% ------------------------------------------------------------------------------
function [o_thermalDetect] = get_ice_thermal_detect_apx_apf11_init_struct

o_thermalDetect = struct( ...
   'sampleTime', [], ...
   'sampleTimeAdj', [], ...
   'sampleNum', [], ...
   'samplePres', [], ...
   'samplePresAdj', [], ...
   'sampleTemp', [], ...
   'medianTempTime', '', ...
   'medianTempTimeAdj', '', ...
   'medianTemp', '', ...
   'detectTime', '', ...
   'detectTimeAdj', '', ...
   'detectPres', '', ...
   'detectPresAdj', '', ...
   'detectNbSample', '' ...
   );

return
