% ------------------------------------------------------------------------------
% Get the basic structure to store Arvor Deep cycle timming information.
%
% SYNTAX :
%  [o_timeStruct] = get_prv_ir_float_time_init_struct(a_cycleNum)
%
% INPUT PARAMETERS :
%   a_cycleNum : cycle number
%
% OUTPUT PARAMETERS :
%   o_timeStruct : cycle timing structure
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHOR : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   12/09/2019 - RNU - creation
% ------------------------------------------------------------------------------
function [o_timeStruct] = get_prv_ir_float_time_init_struct(a_cycleNum)

o_timeStruct = struct( ...
   'cycleNum', a_cycleNum, ...
   'cycleStartDate', [], ...
   'cycleStartDateAdj', [], ...
   'descentToParkStartDate', [], ...
   'descentToParkStartDateAdj', [], ...
   'firstStabDate', [], ...
   'firstStabDateAdj', [], ...
   'firstStabPres', [], ...
   'descentToParkEndDate', [], ...
   'descentToParkEndDateAdj', [], ...
   'descentToProfStartDate', [], ...
   'descentToProfStartDateAdj', [], ...
   'descentToProfEndDate', [], ...
   'descentToProfEndDateAdj', [], ...
   'ascentStartDate', [], ...
   'ascentStartDateAdj', [], ...
   'ascentEndDate', [], ...
   'ascentEndDateAdj', [], ...
   'ascentEndDateBis', [], ... % stored in case RT ICE aborted flag is modified in end of float processing
   'ascentEndDateBisAdj', [], ...
   'transStartDate', [], ...
   'transStartDateAdj', [], ...
   'transStartDateBis', [], ... % stored in case RT ICE aborted flag is modified in end of float processing
   'transStartDateBisAdj', [], ...
   'transEndDate', [], ...
   'transEndDateAdj', [], ...
   'transEndDateCyPrev', [], ...
   'transEndDateCyPrevAdj', [], ...
   'gpsDate', [], ...
   'eolStartDate', [], ...
   'eolStartDateAdj', [], ...
   'firstGroundingDate', [], ...
   'firstGroundingDateAdj', [], ...
   'firstGroundingPres', [], ...
   'secondGroundingDate', [], ...
   'secondGroundingDateAdj', [], ...
   'secondGroundingPres', [], ...
   'groundingDate', [], ...
   'groundingDateAdj', [], ...
   'groundingPres', [], ...
   'firstEmergencyAscentDate', [], ...
   'firstEmergencyAscentDateAdj', [], ...
   'firstEmergencyAscentPres', [], ...
   'emergencyAscentDate', [], ...
   'emergencyAscentDateAdj', [], ...
   'emergencyAscentPres', [], ...
   'iceAscentAbortedFlag', -1, ...
   'cycleClockOffset', [] ...
   );

return
