% ------------------------------------------------------------------------------
% Get the basic structure to store Provor PFV2 tech data.
%
% SYNTAX :
% [o_dataStruct] = get_pfv2_tech_data_init_struct(a_fileType, a_missNum, a_cyNum)
%
% INPUT PARAMETERS :
%   a_fileType : file type (1: self test, 2: tech #1, 3: tech #2, 4: EOL)
%   a_missNum  : mission number
%   a_cyNum    : cycle number
%
% OUTPUT PARAMETERS :
%   o_dataStruct : data initialized structure
%
% EXAMPLES :
%
% SEE ALSO : 
% AUTHORS  : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   06/12/2024 - RNU - creation
% ------------------------------------------------------------------------------
function [o_dataStruct] = get_pfv2_tech_data_init_struct(a_fileType, a_missNum, a_cyNum)

% output parameters initialization
o_dataStruct = struct( ...
   'fileType', a_fileType, ... % 10: self test, 11: tech #1, 12: tech #2, 13: EOL
   'missNum', a_missNum, ...
   'cyNum', a_cyNum, ...
   'label', '', ...
   'techId', '', ...
   'value', '', ...
   'sensorNum', '', ...
   'shortSensorName', '', ...
   'phaseNum', '', ...
   'depthZoneNum', '', ...
   'julD', nan,  ...
   'julDAdj', nan,  ...
   'measCode', -1,  ...
   'groupId', '',  ...
   'pumpFlag', ''  ... % 1 if PUMP, 0 if EV
   );

return
