% ------------------------------------------------------------------------------
% Get the basic structure to store APEX Ice detection information.
%
% SYNTAX :
%  [o_iceDetection] = get_ice_detection_apx_ir_init_struct
%
% INPUT PARAMETERS :
%
% OUTPUT PARAMETERS :
%   o_iceDetection : APEX Ice detection structure
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHOR : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   12/31/2024 - RNU - creation
% ------------------------------------------------------------------------------
function [o_iceDetection] = get_ice_detection_apx_ir_init_struct

% default values
global g_decArgo_dateDef;
global g_decArgo_presDef;

o_iceDetection = struct( ...
   'notEmptyFlag', 0, ...
   'mlSample', [], ...
   'isaTime', g_decArgo_dateDef, ...
   'isaTimeAdj', g_decArgo_dateDef, ...
   'isaFlag', 0, ...
   'isaPres', g_decArgo_presDef, ...
   'isaPresAdj', g_decArgo_presDef, ...
   'evasionTime', g_decArgo_dateDef, ...
   'evasionTimeAdj', g_decArgo_dateDef, ...
   'evasionPres', g_decArgo_presDef, ...
   'evasionPresAdj', g_decArgo_presDef, ...
   'evasionMlt', '', ...
   'evasionNbSamp', '', ...
   'evasionSec', '', ...
   'evasionIer', '', ...
   'evasionPiston', '', ...
   'evasionPerigeeTime', g_decArgo_dateDef, ...
   'evasionPerigeeTimeAdj', g_decArgo_dateDef, ...
   'evasionPerigeePres', g_decArgo_presDef, ...
   'evasionPerigeePresAdj', g_decArgo_presDef, ...
   'satmaskFlag', 0, ...
   'breakupFlag', 0 ...
   );

return
