% ------------------------------------------------------------------------------
% Get the basic structure to store APEX APF11 Ice detection information.
%
% SYNTAX :
%  [o_iceDetection] = get_ice_detection_apx_apf11_init_struct
%
% INPUT PARAMETERS :
%
% OUTPUT PARAMETERS :
%   o_iceDetection : APEX APF11 Ice detection structure
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHOR : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   04/27/2021 - RNU - creation
% ------------------------------------------------------------------------------
function [o_iceDetection] = get_ice_detection_apx_apf11_init_struct

% output parameter
o_iceDetection = struct( ...
   'iceAvoidanceEnabledFlag', '', ...
   'thermalDetect', [], ...
   'breakupDetect', [], ...
   'capDetect', [], ...
   'ascentAbort', [], ...
   'ascentPerigeeTime', '', ...
   'ascentPerigeeTimeAdj', '', ...
   'ascentPerigeePres', '', ...
   'ascentPerigeePresAdj', '', ...
   'iceCycleNumbers', [], ...
   'foundSkyFlag', '' ...
   );

% o_thermalDetect = struct( ...
%    'sampleTime', [], ...
%    'sampleTimeAdj', [], ...
%    'sampleNum', [], ...
%    'samplePres', [], ...
%    'samplePresAdj', [], ...
%    'sampleTemp', [], ...
%    'medianTempTime', '', ...
%    'medianTempTimeAdj', '', ...
%    'medianTemp', '', ...
%    'detectTime', '', ...
%    'detectTimeAdj', '', ...
%    'detectPres', '', ...
%    'detectPresAdj', '', ...
%    'detectNbSample', '' ...
%    );
% 
% o_breakupDetect = struct( ...
%    'detectTime', '', ...
%    'detectTimeAdj', '', ...
%    'detectFlag', '' ...
%    );
% 
% o_capDetect = struct( ...
%    'detectTime', '', ...
%    'detectTimeAdj', '', ...
%    'detectPres', '', ...
%    'detectPresAdj', '', ...
%    'detectTemp', '', ...
%    'detectFlag', '' ...
%    );
% 
% o_ascentAbort = struct( ...
%    'abortTypeTime', '', ...
%    'abortTypeTimeAdj', '', ...
%    'abortType', 0 ...
%    );

return
