% ------------------------------------------------------------------------------
% Print Ice data in CSV file.
%
% SYNTAX :
%  print_ice_info_apx_apf11_in_csv_file(a_iceDetection)
%
% INPUT PARAMETERS :
%   a_iceDetection : Ice detection data
%
% OUTPUT PARAMETERS :
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHOR : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   03/03/2020 - RNU - creation
% ------------------------------------------------------------------------------
function print_ice_info_apx_apf11_in_csv_file(a_iceDetection)

% current float WMO number
global g_decArgo_floatNum;

% current cycle number
global g_decArgo_cycleNum;

% output CSV file Id
global g_decArgo_outputCsvFileId;


if (isempty(a_iceDetection))
   return
end

if (~isempty(a_iceDetection))

   if (~isempty(a_iceDetection.iceAvoidanceEnabledFlag))
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Avoidance enable; %d\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum, ...
         a_iceDetection.iceAvoidanceEnabledFlag);
   end

   if (~isempty(a_iceDetection.thermalDetect))
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Thermal detect #; SAMPLE #; JULD; JULD_ADJUSTED; PRES (decibar); PRES_ADJUSTED (decibar); TEMP (degree_Celsius)\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum);
      for idT = 1:length(a_iceDetection.thermalDetect)
         for idS = 1:length(a_iceDetection.thermalDetect(idT).sampleTime)
            fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Thermal det #%d; #%d; %s; %s; %g; %g; %g\n', ...
               g_decArgo_floatNum, g_decArgo_cycleNum, ...
               idT, ...
               a_iceDetection.thermalDetect(idT).sampleNum(idS), ...
               julian_2_gregorian_dec_argo(a_iceDetection.thermalDetect(idT).sampleTime(idS)), ...
               julian_2_gregorian_dec_argo(a_iceDetection.thermalDetect(idT).sampleTimeAdj(idS)), ...
               a_iceDetection.thermalDetect(idT).samplePres(idS), ...
               a_iceDetection.thermalDetect(idT).samplePresAdj(idS), ...
               a_iceDetection.thermalDetect(idT).sampleTemp(idS));
         end
         if (~isempty(a_iceDetection.thermalDetect(idT).medianTempTime))
            fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Thermal detect #; MEDIAN; JULD; JULD_ADJUSTED; TEMP (degree_Celsius)\n', ...
               g_decArgo_floatNum, g_decArgo_cycleNum);
            fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Thermal det #%d; MEDIAN; %s; %s; %g\n', ...
               g_decArgo_floatNum, g_decArgo_cycleNum, idT, ...
               julian_2_gregorian_dec_argo(a_iceDetection.thermalDetect(idT).medianTempTime), ...
               julian_2_gregorian_dec_argo(a_iceDetection.thermalDetect(idT).medianTempTimeAdj), ...
               a_iceDetection.thermalDetect(idT).medianTemp);
         end
         if (~isempty(a_iceDetection.thermalDetect(idT).detectTime))
            fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Thermal detect #; DETECT; JULD; JULD_ADJUSTED; PRES (decibar); PRES_ADJUSTED (decibar); MEDIAN TEMP (degree_Celsius); NB SAMPLES\n', ...
               g_decArgo_floatNum, g_decArgo_cycleNum);
            fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Thermal det #%d; DETECT; %s; %s; %g; %g; %g; %d\n', ...
               g_decArgo_floatNum, g_decArgo_cycleNum, idT, ...
               julian_2_gregorian_dec_argo(a_iceDetection.thermalDetect(idT).detectTime), ...
               julian_2_gregorian_dec_argo(a_iceDetection.thermalDetect(idT).detectTimeAdj), ...
               a_iceDetection.thermalDetect(idT).detectPres, ...
               a_iceDetection.thermalDetect(idT).detectPresAdj, ...
               a_iceDetection.thermalDetect(idT).medianTemp, ...
               a_iceDetection.thermalDetect(idT).detectNbSample);
         end
      end
   end

   if (~isempty(a_iceDetection.breakupDetect))
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Breakup detect #; JULD; JULD_ADJUSTED; FLAG (1:TRUE, 0:FALSE)\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum);
      for id = 1:length(a_iceDetection.breakupDetect)
         fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Breakup det #%d; %s; %s; %d\n', ...
            g_decArgo_floatNum, g_decArgo_cycleNum, ...
            id, ...
            julian_2_gregorian_dec_argo(a_iceDetection.breakupDetect(id).detectTime), ...
            julian_2_gregorian_dec_argo(a_iceDetection.breakupDetect(id).detectTimeAdj), ...
            a_iceDetection.breakupDetect(id).detectFlag);
      end
   end

   if (~isempty(a_iceDetection.capDetect))
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Ice cap detect #; JULD; JULD_ADJUSTED; PRES (decibar); PRES_ADJUSTED (decibar); TEMP (degree_Celsius); FLAG (1:TRUE, 0:FALSE)\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum);
      for id = 1:length(a_iceDetection.capDetect)
         fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Ice cap det #%d; %s; %s; %g; %g; %g; %d\n', ...
            g_decArgo_floatNum, g_decArgo_cycleNum, ...
            id, ...
            julian_2_gregorian_dec_argo(a_iceDetection.capDetect(id).detectTime), ...
            julian_2_gregorian_dec_argo(a_iceDetection.capDetect(id).detectTimeAdj), ...
            a_iceDetection.capDetect(id).detectPres, ...
            a_iceDetection.capDetect(id).detectPresAdj, ...
            a_iceDetection.capDetect(id).detectTemp, ...
            a_iceDetection.capDetect(id).detectFlag);
      end
   end

   if (~isempty(a_iceDetection.iceCycleNumbers))
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Number of ICe cycles; %d\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum, max(a_iceDetection.iceCycleNumbers));
   end

   if (~isempty(a_iceDetection.ascentAbort))
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Ascent abort; JULD; JULD_ADJUSTED; Type (1:ICE detection, 2:breakup period)\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum);
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Ascent abort; %s; %s; %d\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum, ...
         julian_2_gregorian_dec_argo(a_iceDetection.ascentAbort.abortTypeTime), ...
         julian_2_gregorian_dec_argo(a_iceDetection.ascentAbort.abortTypeTimeAdj), ...
         a_iceDetection.ascentAbort.abortType);
   end

   if (~isempty(a_iceDetection.ascentPerigeeTime))
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Ascent perigee; JULD; JULD_ADJUSTED; PRES (decibar); PRES_ADJUSTED (decibar)\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum);
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Ascent perigee; %s; %s; %g; %g\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum, ...
         julian_2_gregorian_dec_argo(a_iceDetection.ascentPerigeeTime), ...
         julian_2_gregorian_dec_argo(a_iceDetection.ascentPerigeeTimeAdj), ...
         a_iceDetection.ascentPerigeePres, ...
         a_iceDetection.ascentPerigeePresAdj ...
         );
   end

   if (~isempty(a_iceDetection.foundSkyFlag))
      fprintf(g_decArgo_outputCsvFileId, '%d; %d; Ice; Found sky flag; %d\n', ...
         g_decArgo_floatNum, g_decArgo_cycleNum, ...
         a_iceDetection.foundSkyFlag);
   end
end

return
