% ------------------------------------------------------------------------------
% Read the metadata.xml file transmitted by CTS5-USEA floats, compare its
% content to the BDD information and store the metadata in the dedicated
% structure.
%
% SYNTAX :
%  [o_metaStruct] = get_meta_data_cts5(...
%    a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
%    a_floatNum, a_outputCsvDirName, a_rtVersionFlag,a_dacFormatId)
%
% INPUT PARAMETERS :
%   a_metaDataXmlFileName : metadata.xml file
%   a_metaStruct          : input meta-data structure
%   a_sensorListNum       : list of CTS5-USEA sensor numbers
%   a_floatNum            : float WMO number
%   a_outputCsvDirName    : output CSV file directory
%   a_rtVersionFlag       : 1 if it is the RT version of the tool, 0 otherwise
%   a_dacFormatId         : DAC version of the float
%
% OUTPUT PARAMETERS :
%   o_metaStruct : output meta-data structure
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHOR : Jean-Philippe Rannou (Capgemini) (jean.philippe.rannou@partenaire-exterieur.ifremer.fr)
% ------------------------------------------------------------------------------
% RELEASES :
%   02/12/2021 - RNU - creation
% ------------------------------------------------------------------------------
function [o_metaStruct] = get_meta_data_cts5(...
   a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
   a_floatNum, a_outputCsvDirName, a_rtVersionFlag, a_dacFormatId)

% output parameters initialization
o_metaStruct = [];

% retrieve deecId from DAC version
switch (a_dacFormatId)
   case {'7.11', '7.21'}
      [o_metaStruct] = get_meta_data_cts5_126_136(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.12'}
      [o_metaStruct] = get_meta_data_cts5_127(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.13'}
      [o_metaStruct] = get_meta_data_cts5_128(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.14', '7.26'}
      [o_metaStruct] = get_meta_data_cts5_129_141(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.15'}
      [o_metaStruct] = get_meta_data_cts5_130(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.16'}
      [o_metaStruct] = get_meta_data_cts5_131(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.17', '7.22'}
      [o_metaStruct] = get_meta_data_cts5_132_137(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.18'}
      [o_metaStruct] = get_meta_data_cts5_133(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.19'}
      [o_metaStruct] = get_meta_data_cts5_134(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.20'}
      [o_metaStruct] = get_meta_data_cts5_135(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.23'}
      [o_metaStruct] = get_meta_data_cts5_138(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.24'}
      [o_metaStruct] = get_meta_data_cts5_139(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   case {'7.25'}
      [o_metaStruct] = get_meta_data_cts5_140(...
         a_metaDataXmlFileName, a_metaStruct, a_sensorListNum, ...
         a_floatNum, a_outputCsvDirName, a_rtVersionFlag);
   otherwise
      fprintf('ERROR: Cannot find decoderId from DAC version ''%s'' in get_meta_data_cts5\n', ...
         a_dacFormatId);
      return
end

return
