info_dict = {
    "WMO": "6902892",
    "PTT": "300234065895840",
    "FLOAT_TYPE": "PROVOR",
    "DECODER_VERSION": "5.67",
    "DECODER_ID": "221",
    "FRAME_LENGTH": "31",
    "CYCLE_LENGTH": "120",
    "DRIFT_SAMPLING_PERIOD": "3",
    "DELAI": "-1",
    "LAUNCH_DATE": "20210313020600",
    "LAUNCH_LON": "-47.061",
    "LAUNCH_LAT": "-47.013",
    "END_DECODING_DATE": "99999999999999",
    "REFERENCE_DAY": "20210313",
    "DM_FLAG": "0",
}
meta_dict = {
    "ARGO_USER_MANUAL_VERSION": "3.1",
    "PLATFORM_NUMBER": "6902892",
    "PTT": "589584",
    "IMEI": "300234065895840",
    "TRANS_SYSTEM": [{"TRANS_SYSTEM_1": "IRIDIUM"}],
    "TRANS_SYSTEM_ID": [{"TRANS_SYSTEM_ID_1": "n/a"}],
    "TRANS_FREQUENCY": [{"TRANS_FREQUENCY_1": "n/a"}],
    "POSITIONING_SYSTEM": [
        {"POSITIONING_SYSTEM_1": "GPS", "POSITIONING_SYSTEM_2": "IRIDIUM"}
    ],
    "PLATFORM_FAMILY": "FLOAT_DEEP",
    "PLATFORM_TYPE": "ARVOR_D",
    "PLATFORM_MAKER": "NKE",
    "FIRMWARE_VERSION": "5608A14",
    "MANUAL_VERSION": "33-16-028_UTI",
    "FLOAT_SERIAL_NO": "AD2700-18FR005",
    "STANDARD_FORMAT_ID": "n/a",
    "DAC_FORMAT_ID": "5.67",
    "WMO_INST_TYPE": "838",
    "PROJECT_NAME": "GMMC BACI",
    "DATA_CENTRE": "IF",
    "PI_NAME": "Christine PROVOST",
    "ANOMALY": "",
    "BATTERY_TYPE": "n/a",
    "BATTERY_PACKS": "2 WILPA2427B",
    "CONTROLLER_BOARD_TYPE_PRIMARY": "I535",
    "CONTROLLER_BOARD_TYPE_SECONDARY": "",
    "CONTROLLER_BOARD_SERIAL_NO_PRIMARY": "C157946-0088",
    "CONTROLLER_BOARD_SERIAL_NO_SECONDARY": "",
    "SPECIAL_FEATURES": "",
    "FLOAT_OWNER": "IFREMER",
    "OPERATING_INSTITUTION": "LOCEAN",
    "CUSTOMISATION": "",
    "LAUNCH_DATE": "13/03/2021 02:06:00",
    "LAUNCH_LATITUDE": "-47.0137",
    "LAUNCH_LONGITUDE": "-47.0613",
    "LAUNCH_QC": "1",
    "START_DATE": "13/03/2021 02:18:00",
    "START_DATE_QC": "1",
    "STARTUP_DATE": "",
    "STARTUP_DATE_QC": "",
    "DEPLOYMENT_PLATFORM": "SARMIENTO DE GAMBOA",
    "DEPLOYMENT_CRUISE_ID": "SAGA 10W",
    "DEPLOYMENT_REFERENCE_STATION_ID": "yes",
    "END_MISSION_DATE": "",
    "END_MISSION_STATUS": "",
    "END_DECODING_DATE": "",
    "CONFIG_PARAMETER_NAME": [
        {
            "CONFIG_PARAMETER_NAME_1": "CONFIG_PM00_NumberOfCycles",
            "CONFIG_PARAMETER_NAME_2": "CONFIG_PM01_CyclePeriod",
            "CONFIG_PARAMETER_NAME_3": "CONFIG_PM02_ReferenceDay",
            "CONFIG_PARAMETER_NAME_4": "CONFIG_PM03_EstimatedSurfaceTime",
            "CONFIG_PARAMETER_NAME_5": "CONFIG_PM04_DelayBeforeMission",
            "CONFIG_PARAMETER_NAME_6": "CONFIG_PM05_DescentSamplingPeriod",
            "CONFIG_PARAMETER_NAME_7": "CONFIG_PM06_DriftSamplingPeriod",
            "CONFIG_PARAMETER_NAME_8": "CONFIG_PM07_AscentSamplingPeriod",
            "CONFIG_PARAMETER_NAME_9": "CONFIG_PM08_DriftDepth",
            "CONFIG_PARAMETER_NAME_10": "CONFIG_PM09_ProfileDepth",
            "CONFIG_PARAMETER_NAME_11": "CONFIG_PM10_ThresholdSurfaceMiddlePressure",
            "CONFIG_PARAMETER_NAME_12": "CONFIG_PM11_ThresholdMiddleBottomPressure",
            "CONFIG_PARAMETER_NAME_13": "CONFIG_PM12_ThicknessOfTheSurfaceSlices",
            "CONFIG_PARAMETER_NAME_14": "CONFIG_PM13_ThicknessOfTheMiddleSlices",
            "CONFIG_PARAMETER_NAME_15": "CONFIG_PM14_ThicknessOfTheBottomSlices",
            "CONFIG_PARAMETER_NAME_16": "CONFIG_PM15_IridiumEOLTransmissionPeriod",
            "CONFIG_PARAMETER_NAME_17": "CONFIG_PM16_IridiumSecondSessionWaitingTime",
            "CONFIG_PARAMETER_NAME_18": "CONFIG_PM17_PostGroundingWaitingTime",
            "CONFIG_PARAMETER_NAME_19": "CONFIG_PM18_BottomSizeThicknessWhenGrounded",
            "CONFIG_PARAMETER_NAME_20": "CONFIG_PT00_EVMaxDurationOnSurface",
            "CONFIG_PARAMETER_NAME_21": "CONFIG_PT01_EVMaxVolumeDuringDescentAndRepositioning",
            "CONFIG_PARAMETER_NAME_22": "CONFIG_PT02_PumpMaxDurationDuringRepositioning",
            "CONFIG_PARAMETER_NAME_23": "CONFIG_PT03_PumpMaxDurationDuringAscent",
            "CONFIG_PARAMETER_NAME_24": "CONFIG_PT04_PumpDurationDuringBuoyancyAcquisition",
            "CONFIG_PARAMETER_NAME_25": "CONFIG_PT05_PressureTargetToleranceForStabilization",
            "CONFIG_PARAMETER_NAME_26": "CONFIG_PT06_MaxPressureBeforeEmergencyAscent",
            "CONFIG_PARAMETER_NAME_27": "CONFIG_PT07_BuoyancyReductionFirstThreshold",
            "CONFIG_PARAMETER_NAME_28": "CONFIG_PT08_BuoyancyReductionSecondThreshold",
            "CONFIG_PARAMETER_NAME_29": "CONFIG_PT09_NumberOfOutOfTolerancePressuresBeforeRepositioning",
            "CONFIG_PARAMETER_NAME_30": "CONFIG_PT10_GroundingMode",
            "CONFIG_PARAMETER_NAME_31": "CONFIG_PT11_MinOilVolumeForGroundingDetection",
            "CONFIG_PARAMETER_NAME_32": "CONFIG_PT12_MinPressureThresholdToSwitchPressureWhenGrounding",
            "CONFIG_PARAMETER_NAME_33": "CONFIG_PT13_GroundingSwitchPressureAdjustment",
            "CONFIG_PARAMETER_NAME_34": "CONFIG_PT14_PressureTargetToleranceDuringDrift",
            "CONFIG_PARAMETER_NAME_35": "CONFIG_PT16_SecondProfilePressureRepetitionRate",
            "CONFIG_PARAMETER_NAME_36": "CONFIG_PT17_SecondProfilePressure",
            "CONFIG_PARAMETER_NAME_37": "CONFIG_PT18_AverageDescentSpeed",
            "CONFIG_PARAMETER_NAME_38": "CONFIG_PT19_ParkPressureIncrementBetweenCycles",
            "CONFIG_PARAMETER_NAME_39": "CONFIG_PT20_CTDPumpCutOffPressure",
            "CONFIG_PARAMETER_NAME_40": "CONFIG_PT21_OptodeSensorActivationFlag",
            "CONFIG_PARAMETER_NAME_41": "CONFIG_PT22_EndOfAscentPressure",
            "CONFIG_PARAMETER_NAME_42": "CONFIG_PT23_AverageAscentSpeed",
            "CONFIG_PARAMETER_NAME_43": "CONFIG_PT24_PressureCheckPeriodDuringAscent",
            "CONFIG_PARAMETER_NAME_44": "CONFIG_PT25_MinPressureDiffForPumpAction",
            "CONFIG_PARAMETER_NAME_45": "CONFIG_PT26_PressureCheckPeriodDuringDescent",
            "CONFIG_PARAMETER_NAME_46": "CONFIG_PT27_MinPressureDiffForEVAction",
            "CONFIG_PARAMETER_NAME_47": "CONFIG_PT28_NumberOfGpsLocationRetriesBeforeSwitchOffOn",
            "CONFIG_PARAMETER_NAME_48": "CONFIG_PT29_HydraulicPacketsTransmissionFlag",
            "CONFIG_PARAMETER_NAME_49": "CONFIG_PT30_InAirAcquisitionSamplingPeriod",
            "CONFIG_PARAMETER_NAME_50": "CONFIG_PT31_InAirAcquisitionPhaseDuration",
            "CONFIG_PARAMETER_NAME_51": "CONFIG_PT32_InAirPumpActionTimeBuoyancyAcquisition",
            "CONFIG_PARAMETER_NAME_52": "CONFIG_PT33_InAirAcquisitionPeriodicity",
            "CONFIG_PARAMETER_NAME_53": "CONFIG_PT34_IridiumTimeOut",
            "CONFIG_PARAMETER_NAME_54": "CONFIG_PT35_BallastSensorMountedFlag",
            "CONFIG_PARAMETER_NAME_55": "CONFIG_PT36_InternalPressureCalibrationCoefficient1",
            "CONFIG_PARAMETER_NAME_56": "CONFIG_PT37_InternalPressureCalibrationCoefficient2",
            "CONFIG_PARAMETER_NAME_57": "CONFIG_PG00_NbDaysWithoutSurfacingAfterIceDetection",
            "CONFIG_PARAMETER_NAME_58": "CONFIG_PG01_NbDaysWithoutSurfacingBeforeDisablingIceDetection",
            "CONFIG_PARAMETER_NAME_59": "CONFIG_PG02_NbDetectionToConfirmIce",
            "CONFIG_PARAMETER_NAME_60": "CONFIG_PG03_IceDetectionStartPressure",
            "CONFIG_PARAMETER_NAME_61": "CONFIG_PG04_IceDetectionStopPressure",
            "CONFIG_PARAMETER_NAME_62": "CONFIG_PG05_TemperatureThreshold",
            "CONFIG_PARAMETER_NAME_63": "CONFIG_PG06_SlowDownPressure",
            "CONFIG_PARAMETER_NAME_64": "CONFIG_PG07_PressureAcqPeriodDuringSlowAscentPhase",
            "CONFIG_PARAMETER_NAME_65": "CONFIG_PG08_MinPressureDiffForPumpAction",
            "CONFIG_PARAMETER_NAME_66": "CONFIG_PG09_PumpActionDuration",
            "CONFIG_PARAMETER_NAME_67": "CONFIG_PG10_GPSTimeout",
            "CONFIG_PARAMETER_NAME_68": "CONFIG_PG11_FirstIridiumLockTimeout",
            "CONFIG_PARAMETER_NAME_69": "CONFIG_PG12_DelayBeforeAscentBlockingDetection",
            "CONFIG_PARAMETER_NAME_70": "CONFIG_PG13_PressureVariationToEndBuoyancyInversion",
            "CONFIG_PARAMETER_NAME_71": "CONFIG_PG14_OilVolumePerValveAction",
            "CONFIG_PARAMETER_NAME_72": "CONFIG_PG15_OilVolumeMinForGroundingDetection",
            "CONFIG_PARAMETER_NAME_73": "CONFIG_PX00_Direction",
            "CONFIG_PARAMETER_NAME_74": "CONFIG_PX01_CtdCutOffPressure",
            "CONFIG_PARAMETER_NAME_75": "CONFIG_PX02_ProfileCutOffPressure",
            "CONFIG_PARAMETER_NAME_76": "CONFIG_PX03_OptodeVerticalOffset",
            "CONFIG_PARAMETER_NAME_77": "CONFIG_PX04_OptodeAdditionalStick",
            "CONFIG_PARAMETER_NAME_78": "CONFIG_PX05_BitMaskMonthsIceDetectionActive",
        }
    ],
    "CONFIG_PARAMETER_VALUE": [
        {
            "CONFIG_PARAMETER_VALUE_1": "500",
            "CONFIG_PARAMETER_VALUE_2": "5",
            "CONFIG_PARAMETER_VALUE_3": "2",
            "CONFIG_PARAMETER_VALUE_4": "06",
            "CONFIG_PARAMETER_VALUE_5": "15",
            "CONFIG_PARAMETER_VALUE_6": "0",
            "CONFIG_PARAMETER_VALUE_7": "3",
            "CONFIG_PARAMETER_VALUE_8": "10",
            "CONFIG_PARAMETER_VALUE_9": "3000",
            "CONFIG_PARAMETER_VALUE_10": "4000",
            "CONFIG_PARAMETER_VALUE_11": "400",
            "CONFIG_PARAMETER_VALUE_12": "1400",
            "CONFIG_PARAMETER_VALUE_13": "1",
            "CONFIG_PARAMETER_VALUE_14": "5",
            "CONFIG_PARAMETER_VALUE_15": "7",
            "CONFIG_PARAMETER_VALUE_16": "360",
            "CONFIG_PARAMETER_VALUE_17": "20",
            "CONFIG_PARAMETER_VALUE_18": "10",
            "CONFIG_PARAMETER_VALUE_19": "1",
            "CONFIG_PARAMETER_VALUE_20": "1800",
            "CONFIG_PARAMETER_VALUE_21": "17",
            "CONFIG_PARAMETER_VALUE_22": "450",
            "CONFIG_PARAMETER_VALUE_23": "1120",
            "CONFIG_PARAMETER_VALUE_24": "28000",
            "CONFIG_PARAMETER_VALUE_25": "50",
            "CONFIG_PARAMETER_VALUE_26": "4220",
            "CONFIG_PARAMETER_VALUE_27": "4",
            "CONFIG_PARAMETER_VALUE_28": "12",
            "CONFIG_PARAMETER_VALUE_29": "2",
            "CONFIG_PARAMETER_VALUE_30": "0",
            "CONFIG_PARAMETER_VALUE_31": "47",
            "CONFIG_PARAMETER_VALUE_32": "200",
            "CONFIG_PARAMETER_VALUE_33": "100",
            "CONFIG_PARAMETER_VALUE_34": "50",
            "CONFIG_PARAMETER_VALUE_35": "1",
            "CONFIG_PARAMETER_VALUE_36": "4000",
            "CONFIG_PARAMETER_VALUE_37": "27",
            "CONFIG_PARAMETER_VALUE_38": "0",
            "CONFIG_PARAMETER_VALUE_39": "2",
            "CONFIG_PARAMETER_VALUE_40": "1",
            "CONFIG_PARAMETER_VALUE_41": "10",
            "CONFIG_PARAMETER_VALUE_42": "90",
            "CONFIG_PARAMETER_VALUE_43": "2",
            "CONFIG_PARAMETER_VALUE_44": "10",
            "CONFIG_PARAMETER_VALUE_45": "5",
            "CONFIG_PARAMETER_VALUE_46": "4",
            "CONFIG_PARAMETER_VALUE_47": "45",
            "CONFIG_PARAMETER_VALUE_48": "1",
            "CONFIG_PARAMETER_VALUE_49": "30",
            "CONFIG_PARAMETER_VALUE_50": "5",
            "CONFIG_PARAMETER_VALUE_51": "33000",
            "CONFIG_PARAMETER_VALUE_52": "1",
            "CONFIG_PARAMETER_VALUE_53": "120",
            "CONFIG_PARAMETER_VALUE_54": "0",
            "CONFIG_PARAMETER_VALUE_55": "1.463",
            "CONFIG_PARAMETER_VALUE_56": "-107",
            "CONFIG_PARAMETER_VALUE_57": "10",
            "CONFIG_PARAMETER_VALUE_58": "90",
            "CONFIG_PARAMETER_VALUE_59": "3",
            "CONFIG_PARAMETER_VALUE_60": "50",
            "CONFIG_PARAMETER_VALUE_61": "20",
            "CONFIG_PARAMETER_VALUE_62": "-1790",
            "CONFIG_PARAMETER_VALUE_63": "150",
            "CONFIG_PARAMETER_VALUE_64": "2",
            "CONFIG_PARAMETER_VALUE_65": "4",
            "CONFIG_PARAMETER_VALUE_66": "500",
            "CONFIG_PARAMETER_VALUE_67": "5",
            "CONFIG_PARAMETER_VALUE_68": "10",
            "CONFIG_PARAMETER_VALUE_69": "90",
            "CONFIG_PARAMETER_VALUE_70": "20",
            "CONFIG_PARAMETER_VALUE_71": "9",
            "CONFIG_PARAMETER_VALUE_72": "900",
            "CONFIG_PARAMETER_VALUE_73": "",
            "CONFIG_PARAMETER_VALUE_74": "",
            "CONFIG_PARAMETER_VALUE_75": "",
            "CONFIG_PARAMETER_VALUE_76": "-0.3",
            "CONFIG_PARAMETER_VALUE_77": "1",
            "CONFIG_PARAMETER_VALUE_78": "",
        }
    ],
    "CONFIG_MISSION_NUMBER": [{"CONFIG_MISSION_NUMBER_1": "0"}],
    "CONFIG_MISSION_COMMENT": [],
    "CONFIG_REPETITION_RATE": [],
    "SENSOR": [
        {
            "SENSOR_1": "CTD_PRES",
            "SENSOR_2": "CTD_TEMP",
            "SENSOR_3": "CTD_CNDC",
            "SENSOR_4": "OPTODE_DOXY",
        }
    ],
    "SENSOR_MAKER": [
        {
            "SENSOR_MAKER_1": "KISTLER",
            "SENSOR_MAKER_2": "SBE",
            "SENSOR_MAKER_3": "SBE",
            "SENSOR_MAKER_4": "AANDERAA",
        }
    ],
    "SENSOR_MODEL": [
        {
            "SENSOR_MODEL_1": "KISTLER_10153PSIA",
            "SENSOR_MODEL_2": "SBE41CP_V7.2.5",
            "SENSOR_MODEL_3": "SBE41CP_V7.2.5",
            "SENSOR_MODEL_4": "AANDERAA_OPTODE_4330",
        }
    ],
    "SENSOR_SERIAL_NO": [
        {
            "SENSOR_SERIAL_NO_1": "5276539",
            "SENSOR_SERIAL_NO_2": "10978",
            "SENSOR_SERIAL_NO_3": "10978",
            "SENSOR_SERIAL_NO_4": "2961",
        }
    ],
    "PARAMETER_SENSOR": [
        {
            "PARAMETER_SENSOR_1": "CTD_PRES",
            "PARAMETER_SENSOR_2": "CTD_TEMP",
            "PARAMETER_SENSOR_3": "CTD_CNDC",
            "PARAMETER_SENSOR_4": "OPTODE_DOXY",
            "PARAMETER_SENSOR_5": "OPTODE_DOXY",
            "PARAMETER_SENSOR_6": "OPTODE_DOXY",
            "PARAMETER_SENSOR_7": "OPTODE_DOXY",
            "PARAMETER_SENSOR_8": "OPTODE_DOXY",
        }
    ],
    "PARAMETER_UNITS": [
        {
            "PARAMETER_UNITS_1": "decibar",
            "PARAMETER_UNITS_2": "degree_Celsius",
            "PARAMETER_UNITS_3": "psu",
            "PARAMETER_UNITS_4": "degree",
            "PARAMETER_UNITS_5": "degree",
            "PARAMETER_UNITS_6": "degree_Celsius",
            "PARAMETER_UNITS_7": "micromole/kg",
            "PARAMETER_UNITS_8": "millibar",
        }
    ],
    "PARAMETER_ACCURACY": [
        {
            "PARAMETER_ACCURACY_1": "2.4",
            "PARAMETER_ACCURACY_2": "0.002",
            "PARAMETER_ACCURACY_3": "0.005",
            "PARAMETER_ACCURACY_4": "",
            "PARAMETER_ACCURACY_5": "",
            "PARAMETER_ACCURACY_6": "",
            "PARAMETER_ACCURACY_7": "8 umol/kg or 10%",
            "PARAMETER_ACCURACY_8": "",
        }
    ],
    "PARAMETER_RESOLUTION": [
        {
            "PARAMETER_RESOLUTION_1": "0.1",
            "PARAMETER_RESOLUTION_2": "0.001",
            "PARAMETER_RESOLUTION_3": "0.001",
            "PARAMETER_RESOLUTION_4": "0.002",
            "PARAMETER_RESOLUTION_5": "0.002",
            "PARAMETER_RESOLUTION_6": "0.001",
            "PARAMETER_RESOLUTION_7": "1 umol/kg",
            "PARAMETER_RESOLUTION_8": "",
        }
    ],
    "PARAMETER": [
        {
            "PARAMETER_1": "PRES",
            "PARAMETER_2": "TEMP",
            "PARAMETER_3": "PSAL",
            "PARAMETER_4": "C1PHASE_DOXY",
            "PARAMETER_5": "C2PHASE_DOXY",
            "PARAMETER_6": "TEMP_DOXY",
            "PARAMETER_7": "DOXY",
            "PARAMETER_8": "PPOX_DOXY",
        }
    ],
    "PREDEPLOYMENT_CALIB_EQUATION": [
        {
            "PREDEPLOYMENT_CALIB_EQUATION_1": "n/a",
            "PREDEPLOYMENT_CALIB_EQUATION_2": "n/a",
            "PREDEPLOYMENT_CALIB_EQUATION_3": "n/a",
            "PREDEPLOYMENT_CALIB_EQUATION_4": "n/a",
            "PREDEPLOYMENT_CALIB_EQUATION_5": "n/a",
            "PREDEPLOYMENT_CALIB_EQUATION_6": "n/a",
            "PREDEPLOYMENT_CALIB_EQUATION_7": "n/a",
            "PREDEPLOYMENT_CALIB_EQUATION_8": "n/a",
        }
    ],
    "PREDEPLOYMENT_CALIB_COEFFICIENT": [
        {
            "PREDEPLOYMENT_CALIB_COEFFICIENT_1": "n/a",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_2": "n/a",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_3": "n/a",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_4": "n/a",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_5": "n/a",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_6": "n/a",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_7": "n/a",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_8": "n/a",
        }
    ],
    "PREDEPLOYMENT_CALIB_COMMENT": [],
    "CALIB_RT_PARAMETER": [{"CALIB_RT_PARAMETER_1": "DOXY"}],
    "CALIB_RT_EQUATION": [
        {
            "CALIB_RT_EQUATION_1": "PPOX_DOXY_ADJUSTED = PPOX_DOXY_ADJUSTED = (SLOPE * (1+DRIFT/100*prof_date_juld y launch_date_juld)/365) + INCLINE_T * TEMP)(PPOX_DOXY + OFFSET)"
        }
    ],
    "CALIB_RT_COEFFICIENT": [
        {
            "CALIB_RT_COEFFICIENT_1": "slope=1.0784,offset=0.00,drift=0.000,incline_t=0.000000"
        }
    ],
    "CALIB_RT_COMMENT": [
        {
            "CALIB_RT_COMMENT_1": "initial assessment by coriolis according to https://doi.org/10.13155/76709 based on case1_2 (cycles 2  3  4  5  6)"
        }
    ],
    "CALIB_RT_ADJUSTED_ERROR": [{"CALIB_RT_ADJUSTED_ERROR_1": "10"}],
    "CALIB_RT_ADJ_ERROR_METHOD": [{"CALIB_RT_ADJ_ERROR_METHOD_1": "1_2"}],
    "CALIB_RT_DATE": [{"CALIB_RT_DATE_1": "20210313020600"}],
    "CALIBRATION_COEFFICIENT": [
        {
            "OPTODE": {
                "SVUFoilCoef0": 2.8005640e-03,
                "SVUFoilCoef1": 1.1968740e-04,
                "SVUFoilCoef2": 2.4448620e-06,
                "SVUFoilCoef3": 1.8758690e02,
                "SVUFoilCoef4": -2.3334550e-01,
                "SVUFoilCoef5": -4.5405820e01,
                "SVUFoilCoef6": 3.7045000e00,
                "PhaseCoef0": -1.496,
                "PhaseCoef1": 1,
                "PhaseCoef2": 0,
                "PhaseCoef3": 0,
            }
        }
    ],
    "SENSOR_MOUNTED_ON_FLOAT": [
        {"SENSOR_MOUNTED_ON_FLOAT_1": "CTD", "SENSOR_MOUNTED_ON_FLOAT_2": "OPTODE"}
    ],
    "CP_COR": [],
    "RT_OFFSET": [
        {
            "PARAM": {"PARAM_101": "DOXY"},
            "SLOPE": {"SLOPE_101": "1.0784"},
            "VALUE": {"VALUE_101": "0.00"},
            "DRIFT": {"DRIFT_101": "0.000"},
            "INCLINE": {"INCLINE_101": "0.000000"},
            "ADJUSTED_ERROR": {"ADJUSTED_ERROR_101": "10"},
            "ADJUSTED_ERROR_METHOD": {"ADJUSTED_ERROR_METHOD_101": "1_2"},
            "DATE": {"DATE_101": "20210313020600"},
        }
    ],
}
conf_dict = {
    "FLOAT_LIST_FILE_NAME": "",
    "EXPECTED_CYCLE_LIST": "99999",
    "FLOAT_TRANSMISSION_TYPE": "3",
    "DIR_INPUT_JSON_FLOAT_DECODING_PARAMETERS_FILE": "/mnt/data/config/decArgo_config_floats/json_float_info/",
    "HEX_ARGOS_FILE_FORMAT": "",
    "DIR_INPUT_HEX_ARGOS_FILE_FORMAT_1": "",
    "DIR_INPUT_HEX_ARGOS_FILE_FORMAT_2": "",
    "HEX_ARGOS_DATA_DIRECTORY_STRUCTURE": "",
    "DIR_INPUT_RSYNC_DATA": "/mnt/data/rsync/archive/cycle/",
    "DIR_INPUT_RSYNC_LOG": "/mnt/data/rsync/rsync_list/",
    "DIR_INPUT_JSON_TECH_LABEL_FILE": "/app/config/_techParamNames/",
    "DIR_INPUT_JSON_CONF_LABEL_FILE": "/app/config/_configParamNames/",
    "DIR_INPUT_JSON_FLOAT_META_DATA_FILE": "/mnt/data/config/decArgo_config_floats/json_float_meta_ir_sbd/",
    "DIR_INPUT_DM_BUFFER_LIST": "/mnt/data/config/decArgo_config_floats/float_dm_buffer_lists",
    "IRIDIUM_DATA_DIRECTORY": "/mnt/data/output/iridium/",
    "DIR_OUTPUT_LOG_FILE": "/mnt/data/output/log/",
    "DIR_OUTPUT_CSV_FILE": "/mnt/data/output/csv/",
    "DIR_OUTPUT_XML_FILE": "/mnt/data/output/xml/",
    "DIR_OUTPUT_NETCDF_FILE": "/mnt/data/output/nc/",
    "DIR_OUTPUT_NETCDF_TRAJ_3_2_FILE": "/mnt/data/output/nc/",
    "PROCESS_REMAINING_BUFFERS": "0",
    "GENERATE_NC_MULTI_PROF": "0",
    "GENERATE_NC_MONO_PROF": "2",
    "GENERATE_NC_TECH": "2",
    "GENERATE_NC_META": "2",
    "GENERATE_NC_TRAJ_3_1": "0",
    "GENERATE_NC_TRAJ_3_2": "2",
    "ADD_ARGOS_ERROR_ELLIPSES": "0",
    "DIR_INPUT_ARGOS_ERROR_ELLIPSES_MAIL": "",
    "DIR_INPUT_ARGOS_ERROR_ELLIPSES_WS_SPOOL": "",
    "DIR_INPUT_ARGOS_ERROR_ELLIPSES_WS_ARCHIVE": "",
    "APPLY_RTQC": "0",
    "TEST001_PLATFORM_IDENTIFICATION": "1",
    "TEST002_IMPOSSIBLE_DATE": "1",
    "TEST003_IMPOSSIBLE_LOCATION": "1",
    "TEST004_POSITION_ON_LAND": "1",
    "TEST005_IMPOSSIBLE_SPEED": "1",
    "TEST006_GLOBAL_RANGE": "1",
    "TEST007_REGIONAL_RANGE": "1",
    "TEST008_PRESSURE_INCREASING": "1",
    "TEST009_SPIKE": "1",
    "TEST011_GRADIENT": "1",
    "TEST012_DIGIT_ROLLOVER": "1",
    "TEST013_STUCK_VALUE": "1",
    "TEST014_DENSITY_INVERSION": "1",
    "TEST015_GREY_LIST": "1",
    "TEST016_GROSS_SALINITY_OR_TEMPERATURE_SENSOR_DRIFT": "0",
    "TEST018_FROZEN_PRESSURE": "0",
    "TEST019_DEEPEST_PRESSURE": "1",
    "TEST020_QUESTIONABLE_ARGOS_POSITION": "1",
    "TEST021_NS_UNPUMPED_SALINITY": "1",
    "TEST022_NS_MIXED_AIR_WATER": "1",
    "TEST023_DEEP_FLOAT": "1",
    "TEST024_RBR_FLOAT": "1",
    "TEST025_MEDD": "1",
    "TEST026_TEMP_CNDC": "1",
    "TEST056_PH": "1",
    "TEST057_DOXY": "1",
    "TEST059_NITRATE": "1",
    "TEST062_BBP": "1",
    "TEST063_CHLA": "1",
    "TEST004_GEBCO_FILE": "/mnt/ref/gebco.nc",
    "TEST015_GREY_LIST_FILE": "/tmp/ar_greylist.txt",
    "WOA_FILE": "/mnt/ref/woa13_all_n00_01.nc",
    "CHLA_COR_FACT_FILE": "/mnt/ref/SLOPE_RT_2024.txt",
    "ADD_THREE_MINUTES": "0",
}
